import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";
import AuthProvider from "@/libs/auth/provider";

const prompt = Prompt({
  variable: "--font-geist-sans",
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.className}`}>
        <AuthProvider>
          <Navber />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
